-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.assigned_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  athlete_id uuid NOT NULL,
  program_template_id uuid,
  nutrition_plan_id uuid,
  start_date date DEFAULT CURRENT_DATE,
  end_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  assigned_at timestamp with time zone DEFAULT now(),
  assigned_by uuid,
  CONSTRAINT assigned_plans_pkey PRIMARY KEY (id),
  CONSTRAINT assigned_plans_user_id_fkey FOREIGN KEY (athlete_id) REFERENCES public.profiles(id),
  CONSTRAINT assigned_plans_program_template_id_fkey FOREIGN KEY (program_template_id) REFERENCES public.program_templates(id),
  CONSTRAINT assigned_plans_nutrition_plan_id_fkey FOREIGN KEY (nutrition_plan_id) REFERENCES public.nutrition_plans(id),
  CONSTRAINT assigned_plans_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.athlete_measurements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  measurement_date date NOT NULL DEFAULT CURRENT_DATE,
  weight_kg numeric,
  weight_change_kg numeric,
  waist_cm numeric,
  neck_cm numeric,
  hips_cm numeric,
  tricep_mm numeric,
  subscapular_mm numeric,
  suprailiac_mm numeric,
  midaxillary_mm numeric,
  bicep_mm numeric,
  lower_back_mm numeric,
  calf_mm numeric,
  body_fat_percentage numeric,
  body_fat_override numeric,
  lean_body_mass_kg numeric,
  fat_mass_kg numeric,
  basal_metabolic_rate numeric,
  calculation_method USER-DEFINED,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  chest_mm numeric,
  abdominal_mm numeric,
  thigh_mm numeric,
  CONSTRAINT athlete_measurements_pkey PRIMARY KEY (id),
  CONSTRAINT athlete_measurements_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT athlete_measurements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.athlete_supplements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  supplement_id uuid NOT NULL,
  prescribed_by uuid NOT NULL,
  dosage text NOT NULL,
  timing text,
  schedule text NOT NULL,
  notes text,
  start_date date NOT NULL,
  end_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT athlete_supplements_pkey PRIMARY KEY (id),
  CONSTRAINT athlete_supplements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT athlete_supplements_supplement_id_fkey FOREIGN KEY (supplement_id) REFERENCES public.supplements(id),
  CONSTRAINT athlete_supplements_prescribed_by_fkey FOREIGN KEY (prescribed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.body_metrics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  check_in_id uuid NOT NULL UNIQUE,
  weight_kg double precision CHECK (weight_kg >= 0::double precision),
  body_fat_percentage double precision CHECK (body_fat_percentage >= 0::double precision AND body_fat_percentage <= 100::double precision),
  waist_cm double precision CHECK (waist_cm >= 0::double precision),
  hip_cm double precision CHECK (hip_cm >= 0::double precision),
  chest_cm double precision CHECK (chest_cm >= 0::double precision),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  left_arm_cm double precision CHECK (left_arm_cm >= 0::double precision),
  right_arm_cm double precision CHECK (right_arm_cm >= 0::double precision),
  left_thigh_cm double precision CHECK (left_thigh_cm >= 0::double precision),
  right_thigh_cm double precision CHECK (right_thigh_cm >= 0::double precision),
  CONSTRAINT body_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT body_metrics_check_in_id_fkey FOREIGN KEY (check_in_id) REFERENCES public.check_ins(id)
);
CREATE TABLE public.check_ins (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  check_in_date date NOT NULL DEFAULT CURRENT_DATE,
  photos jsonb,
  video_url text,
  diet_adherence text,
  training_adherence text,
  steps_adherence text,
  notes text,
  coach_feedback text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT check_ins_pkey PRIMARY KEY (id),
  CONSTRAINT check_ins_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.completed_exercise_sets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workout_session_id uuid NOT NULL,
  exercise_instance_id uuid NOT NULL,
  set_order integer NOT NULL,
  weight text,
  reps integer,
  is_completed boolean DEFAULT false,
  notes text,
  set_type text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT completed_exercise_sets_pkey PRIMARY KEY (id),
  CONSTRAINT completed_exercise_sets_workout_session_id_fkey FOREIGN KEY (workout_session_id) REFERENCES public.workout_sessions(id),
  CONSTRAINT completed_exercise_sets_exercise_instance_id_fkey FOREIGN KEY (exercise_instance_id) REFERENCES public.exercise_instances(id)
);
CREATE TABLE public.device_connections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  device_type text NOT NULL,
  access_token text NOT NULL,
  refresh_token text,
  last_synced timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  token_type text,
  CONSTRAINT device_connections_pkey PRIMARY KEY (id),
  CONSTRAINT device_connections_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.exercise_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workout_session_id uuid NOT NULL,
  exercise_instance_id uuid NOT NULL,
  pain_level integer CHECK (pain_level >= 1 AND pain_level <= 5),
  pump_level integer CHECK (pump_level >= 1 AND pump_level <= 5),
  workload_level integer CHECK (workload_level >= 1 AND workload_level <= 5),
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT exercise_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT exercise_feedback_workout_session_id_fkey FOREIGN KEY (workout_session_id) REFERENCES public.workout_sessions(id),
  CONSTRAINT exercise_feedback_exercise_instance_id_fkey FOREIGN KEY (exercise_instance_id) REFERENCES public.exercise_instances(id)
);
CREATE TABLE public.exercise_instances (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workout_id uuid NOT NULL,
  exercise_db_id integer,
  exercise_name text NOT NULL,
  sets text,
  reps text,
  rest_period_seconds integer CHECK (rest_period_seconds >= 0),
  tempo text,
  notes text,
  order_in_workout integer CHECK (order_in_workout >= 0),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  set_type text,
  sets_data text,
  each_side boolean DEFAULT false,
  group_id uuid,
  group_type USER-DEFINED DEFAULT 'none'::exercise_group_type,
  group_order integer DEFAULT 0,
  is_bodyweight boolean DEFAULT false,
  notes_en text,
  notes_pt text,
  CONSTRAINT exercise_instances_pkey PRIMARY KEY (id),
  CONSTRAINT exercise_instances_workout_id_fkey FOREIGN KEY (workout_id) REFERENCES public.workouts(id),
  CONSTRAINT fk_exercise_instance_exercise FOREIGN KEY (exercise_db_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.exercise_sets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  exercise_instance_id uuid NOT NULL,
  set_order integer NOT NULL,
  type text NOT NULL,
  reps text,
  weight text,
  rest_seconds integer,
  duration text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT exercise_sets_pkey PRIMARY KEY (id),
  CONSTRAINT exercise_sets_exercise_instance_id_fkey FOREIGN KEY (exercise_instance_id) REFERENCES public.exercise_instances(id)
);
CREATE TABLE public.exercises (
  id integer NOT NULL,
  name text NOT NULL,
  original_name text,
  description text,
  slug text,
  primary_muscle_group text,
  secondary_muscle_groups ARRAY,
  gif_url text,
  youtube_link text,
  instructions ARRAY,
  tips ARRAY,
  note text,
  type text,
  body_part text,
  equipment text,
  gender text,
  target text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  name_en text,
  name_pt text,
  description_en text,
  description_pt text,
  CONSTRAINT exercises_pkey PRIMARY KEY (id)
);
CREATE TABLE public.extra_meal_food_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  meal_log_id uuid NOT NULL,
  food_item_id uuid NOT NULL,
  quantity numeric NOT NULL,
  unit character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT extra_meal_food_items_pkey PRIMARY KEY (id),
  CONSTRAINT extra_meal_food_items_meal_log_id_fkey FOREIGN KEY (meal_log_id) REFERENCES public.meal_logs(id),
  CONSTRAINT extra_meal_food_items_food_item_id_fkey FOREIGN KEY (food_item_id) REFERENCES public.food_items(id)
);
CREATE TABLE public.food_item_images (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  food_item_id uuid NOT NULL,
  image_url text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT food_item_images_pkey PRIMARY KEY (id),
  CONSTRAINT food_item_images_food_item_id_fkey FOREIGN KEY (food_item_id) REFERENCES public.food_items(id),
  CONSTRAINT food_item_images_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.food_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  afcd_id text UNIQUE,
  food_name text NOT NULL,
  food_group text,
  calories_per_100g double precision CHECK (calories_per_100g >= 0::double precision),
  protein_per_100g double precision CHECK (protein_per_100g >= 0::double precision),
  carbs_per_100g double precision CHECK (carbs_per_100g >= 0::double precision),
  fat_per_100g double precision CHECK (fat_per_100g >= 0::double precision),
  fiber_per_100g double precision CHECK (fiber_per_100g >= 0::double precision),
  serving_size_g double precision CHECK (serving_size_g > 0::double precision),
  serving_size_unit text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  nutrient_basis text NOT NULL DEFAULT '100g'::text,
  barcode text,
  source text DEFAULT 'ausnut'::text CHECK (source = ANY (ARRAY['ausnut'::text, 'usda'::text, 'open_food_facts'::text, 'custom'::text])),
  created_by uuid,
  is_verified boolean DEFAULT false,
  brand text,
  source_id text,
  food_name_en text,
  food_name_pt text,
  CONSTRAINT food_items_pkey PRIMARY KEY (id),
  CONSTRAINT food_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.meal_food_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  meal_id uuid NOT NULL,
  food_item_id uuid NOT NULL,
  quantity double precision NOT NULL CHECK (quantity > 0::double precision),
  unit text NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  recipe_id uuid,
  source_recipe_id uuid,
  CONSTRAINT meal_food_items_pkey PRIMARY KEY (id),
  CONSTRAINT meal_food_items_meal_id_fkey FOREIGN KEY (meal_id) REFERENCES public.meals(id),
  CONSTRAINT meal_food_items_food_item_id_fkey FOREIGN KEY (food_item_id) REFERENCES public.food_items(id),
  CONSTRAINT meal_food_items_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.recipes(id),
  CONSTRAINT meal_food_items_source_recipe_id_fkey FOREIGN KEY (source_recipe_id) REFERENCES public.recipes(id)
);
CREATE TABLE public.meal_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  meal_id uuid,
  nutrition_plan_id uuid NOT NULL,
  name character varying NOT NULL,
  date date NOT NULL,
  time time without time zone NOT NULL,
  day_type character varying NOT NULL,
  notes text,
  is_extra_meal boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meal_logs_pkey PRIMARY KEY (id),
  CONSTRAINT meal_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT meal_logs_meal_id_fkey FOREIGN KEY (meal_id) REFERENCES public.meals(id),
  CONSTRAINT meal_logs_nutrition_plan_id_fkey FOREIGN KEY (nutrition_plan_id) REFERENCES public.nutrition_plans(id)
);
CREATE TABLE public.meals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  nutrition_plan_id uuid NOT NULL,
  name text NOT NULL,
  time_suggestion text,
  notes text,
  order_in_plan integer CHECK (order_in_plan >= 0),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  day_type text,
  description text,
  name_en text,
  name_pt text,
  notes_en text,
  notes_pt text,
  CONSTRAINT meals_pkey PRIMARY KEY (id),
  CONSTRAINT meals_nutrition_plan_id_fkey FOREIGN KEY (nutrition_plan_id) REFERENCES public.nutrition_plans(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  recipient_id uuid NOT NULL,
  sender_id uuid,
  type character varying NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  related_entity_id uuid,
  related_entity_type character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.profiles(id),
  CONSTRAINT notifications_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.nutrition_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  coach_id uuid NOT NULL,
  name text NOT NULL,
  total_calories real CHECK (total_calories >= 0::double precision),
  protein_grams real CHECK (protein_grams >= 0::double precision),
  carbohydrate_grams real CHECK (carbohydrate_grams >= 0::double precision),
  fat_grams real CHECK (fat_grams >= 0::double precision),
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_public boolean NOT NULL DEFAULT false,
  description_en text,
  description_pt text,
  CONSTRAINT nutrition_plans_pkey PRIMARY KEY (id),
  CONSTRAINT nutrition_plans_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid UNIQUE,
  username text UNIQUE,
  email text NOT NULL UNIQUE,
  role text NOT NULL DEFAULT 'athlete'::text,
  coach_id uuid,
  age integer,
  weight_kg double precision,
  height_cm double precision,
  body_fat_percentage double precision,
  goal_target_fat_loss_kg double precision,
  goal_timeframe_weeks integer,
  goal_target_weight_kg double precision,
  goal_physique_details text,
  training_days_per_week integer,
  training_current_program text,
  training_equipment text,
  training_session_length_minutes integer,
  training_intensity text,
  nutrition_meal_patterns text,
  nutrition_tracking_method text,
  nutrition_preferences text,
  nutrition_allergies text,
  lifestyle_sleep_hours double precision,
  lifestyle_stress_level integer,
  lifestyle_water_intake_liters double precision,
  lifestyle_schedule_notes text,
  supplements_meds text,
  motivation_readiness text,
  onboarding_complete boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  invitation_status character varying,
  invited_at timestamp with time zone,
  gender character varying DEFAULT 'male'::character varying CHECK (gender::text = ANY (ARRAY['male'::character varying, 'female'::character varying]::text[])),
  first_name text,
  last_name text,
  goal_type text CHECK (goal_type = ANY (ARRAY['fat_loss'::text, 'muscle_gain'::text, 'both'::text, 'maintenance'::text])),
  goal_target_muscle_gain_kg numeric,
  experience_level text,
  training_time_of_day text,
  nutrition_wakeup_time_of_day text,
  nutrition_bed_time_of_day text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT profiles_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.program_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  coach_id uuid NOT NULL,
  name text NOT NULL,
  phase text,
  weeks integer NOT NULL CHECK (weeks > 0),
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_public boolean NOT NULL DEFAULT false,
  version integer NOT NULL DEFAULT 1,
  parent_template_id uuid,
  is_latest_version boolean NOT NULL DEFAULT true,
  fitness_level text,
  description_en text,
  description_pt text,
  CONSTRAINT program_templates_pkey PRIMARY KEY (id),
  CONSTRAINT program_templates_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES public.profiles(id),
  CONSTRAINT program_templates_parent_template_id_fkey FOREIGN KEY (parent_template_id) REFERENCES public.program_templates(id)
);
CREATE TABLE public.recipe_ingredients (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  recipe_id uuid NOT NULL,
  food_item_id uuid NOT NULL,
  quantity double precision NOT NULL CHECK (quantity > 0::double precision),
  unit text NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT recipe_ingredients_pkey PRIMARY KEY (id),
  CONSTRAINT recipe_ingredients_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.recipes(id),
  CONSTRAINT recipe_ingredients_food_item_id_fkey FOREIGN KEY (food_item_id) REFERENCES public.food_items(id)
);
CREATE TABLE public.recipes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  coach_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  instructions text,
  total_calories double precision CHECK (total_calories >= 0::double precision),
  total_protein double precision CHECK (total_protein >= 0::double precision),
  total_carbs double precision CHECK (total_carbs >= 0::double precision),
  total_fat double precision CHECK (total_fat >= 0::double precision),
  serving_size double precision CHECK (serving_size > 0::double precision),
  serving_unit text DEFAULT 'g'::text,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT recipes_pkey PRIMARY KEY (id),
  CONSTRAINT recipes_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.step_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  date date NOT NULL,
  step_count integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT step_entries_pkey PRIMARY KEY (id),
  CONSTRAINT step_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.step_goals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  daily_steps integer NOT NULL CHECK (daily_steps >= 0),
  assigned_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT step_goals_pkey PRIMARY KEY (id),
  CONSTRAINT step_goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.supplement_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT supplement_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.supplement_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  athlete_supplement_id uuid NOT NULL,
  taken_at timestamp with time zone NOT NULL DEFAULT now(),
  date date NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT supplement_logs_pkey PRIMARY KEY (id),
  CONSTRAINT supplement_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT supplement_logs_athlete_supplement_id_fkey FOREIGN KEY (athlete_supplement_id) REFERENCES public.athlete_supplements(id)
);
CREATE TABLE public.supplements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  category text NOT NULL,
  default_dosage text,
  default_timing text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  name_en text,
  name_pt text,
  CONSTRAINT supplements_pkey PRIMARY KEY (id)
);
CREATE TABLE public.unit_conversions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  from_unit text NOT NULL,
  to_unit text NOT NULL,
  food_category text,
  conversion_factor double precision NOT NULL,
  CONSTRAINT unit_conversions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.water_goals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  water_goal_ml integer NOT NULL DEFAULT 2500,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT water_goals_pkey PRIMARY KEY (id),
  CONSTRAINT water_goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.water_tracking (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  date date NOT NULL,
  amount_ml integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT water_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT water_tracking_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.wellness_metrics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  check_in_id uuid NOT NULL UNIQUE,
  sleep_hours double precision CHECK (sleep_hours >= 0::double precision),
  sleep_quality integer CHECK (sleep_quality >= 1 AND sleep_quality <= 5),
  stress_level integer CHECK (stress_level >= 1 AND stress_level <= 5),
  fatigue_level integer CHECK (fatigue_level >= 1 AND fatigue_level <= 5),
  digestion text,
  motivation_level integer CHECK (motivation_level >= 1 AND motivation_level <= 5),
  menstrual_cycle_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wellness_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT wellness_metrics_check_in_id_fkey FOREIGN KEY (check_in_id) REFERENCES public.check_ins(id)
);
CREATE TABLE public.workout_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  workout_id uuid NOT NULL,
  start_time timestamp with time zone DEFAULT now(),
  end_time timestamp with time zone,
  duration_seconds integer,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT workout_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT workout_sessions_workout_id_fkey FOREIGN KEY (workout_id) REFERENCES public.workouts(id)
);
CREATE TABLE public.workouts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  program_template_id uuid NOT NULL,
  name text NOT NULL,
  day_of_week integer CHECK (day_of_week >= 1 AND day_of_week <= 7),
  week_number integer CHECK (week_number > 0),
  order_in_program integer,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  name_en text,
  name_pt text,
  description_en text,
  description_pt text,
  CONSTRAINT workouts_pkey PRIMARY KEY (id),
  CONSTRAINT workouts_program_template_id_fkey FOREIGN KEY (program_template_id) REFERENCES public.program_templates(id)
);